### PR TITLE
Vistatec/sle 15 sp5 locdrop3 unversioned localisation checkin

### PR DESCRIPTION
**Pull request by ptinley-vt**
### PR creator: Description

Delivering localised XML and graphics files for the 2 'unversioned' books from SLE 15 SP5, locdrop 3.

1. article-security-pcidss
2. SLES-container

### PR creator: Are there any relevant issues/feature requests?

None.

### CODE REVIEW

**Comment by tomschr** [comment]
Just a hint: there were conflicts with some files which I solved. If you need to pull this branch, use `git pull --rebase`.

**Comment by jfaltenbacher** [comment]
I have run validation checks, removed the edit urls and build the pdf. Both books look good and can be published.
Just noticed, that the Container guide does not mention the code stream on title page; is this on purpose?

**Comment by taroth21** [comment]
> I have run validation checks, removed the edit urls and build the pdf. Both books look good and can be published. Just noticed, that the Container guide does not mention the code stream on title page; is this on purpose?

Good question, maybe it even applies to Codestream 12 and 15 - let's double-check with the writer. But if not the codestream, IMHO at least the product name should be on the title page (it also is missing in the English version, btw).

**Review by taroth21 — CHANGES_REQUESTED** [review]
I noticed two more issues (one is present also in the English source code)

- spelling of the guide name ('Container guide' with lowercase 'guide' - as opposed to all other guide titles we have) 
- GNU Free Documentation License has been translated (usually we keep it in English - maybe it was not flagged correctly in the bigfile we handed off)

**Comment by taroth21** [comment]
Clarifying the questions above with the writer is WIP, but for now, let's merge this anyway. As it's 'mechanical' fixes only we can apply the fixes above in both English and the localized version ourselves afterwards, if needed.

**Pull request merged**
