### PR TITLE
New section of Trento compatibility matrix

### PR DESCRIPTION
**Pull request by tomschr**
### PR creator: Description

A section providing a compatibility matrix between Trento Server and Trento Agents

### Confluence

    https://confluence.suse.com/display/TRNT/2023-08-16+Trento+Documentation

### CODE REVIEW

**Review by abravosuse — COMMENTED** [review]
Not sure to understand the table structure @tomschr . In the first column we should have all the Trento Server versions. And in the first row, all the available agent versions.

**Comment by tomschr** [comment]
> Not sure to understand the table structure @tomschr . In the first column we should have all the Trento Server versions. And in the first row, all the available agent versions.

Maybe I misunderstood you. My understanding was that the mapping from Trento Server version to Trento Agent versions is more of a 1:n relationship. I had something like this in my mind (versions are just examples, not real):

| Trento Server version | Trento Agent version(s) | Note |
|-----------------------|-------------------------|------|
| 1.2.3                 | 2.0.0, 2.1.0            |      |

Maybe in the future, the team introduces some incompatibilities and the table could look like:

| Trento Server version | Trento Agent version(s) | Note |
|-----------------------|-------------------------|------|
| 1.2.3                 | 2.0.0, 2.1.0            |      |
| 2.0.0                 | 2.1.0, 2.2.0            |      |

Perhaps we don't need the note. Would that work?

**Comment by abravosuse** [comment]
I guess that could work, but I had a different representation in mind. I don't know how to create a table here, so I will instead send you a screenshot by slack.

**Comment by tomschr** [comment]
We came up with this result:

Screenshot_20230817_121417

**Review by abravosuse — APPROVED** [review]
Looks good to me!

**Pull request merged**
